### ISSUE TITLE
codes #1

### ISSUE THREAD

**Issue by AhmedMahmoad** [AhmedMahmoad/ASUMobiCarG24#11]
uploading the Arduino codes into  Repository for every single part of project (driving motors ;Bluetooth module ,line tracking ,ultrasonic sensor ..etc..).

**Comment by islamshaabaan** [comment]
I uploaded line tracking code into Project file.

**Comment by AhmedMahmoad** [comment]
we  already know that you don't have to comment -_

**Comment by eslamkashaf** [comment]
hahahhh
